  version: '3'
  services:
    homeassistant:
      container_name: home-assistant
      image: homeassistant/home-assistant:0.78.2
      volumes:
        - ./configuration:/config
        - /etc/localtime:/etc/localtime:ro
      restart: always
      network_mode: host
    smart_home:
      container_name: