- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: sensor.door_living
      to: 'open'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm
  
- alias: 'Send notification when alarm triggered'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'triggered'
  action:
    - service: notify.alarm_notify
      data:
        message: '{ "message" : "triggered"}'
